BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "tl3572"
BBFILE_PATTERN_tl3572 = "^${LAYERDIR}/"
BBFILE_PRIORITY_tl3572 = "20"
LAYERSERIES_COMPAT_tl3572 = "kirkstone"

