BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "tl3572_stage2"
BBFILE_PATTERN_tl3572_stage2 = "^${LAYERDIR}/"
BBFILE_PRIORITY_tl3572_stage2 = "20"
LAYERSERIES_COMPAT_tl3572_stage2 = "kirkstone"
