/* P0 portable MN core. Hardware and application integration are not supplied. */
#ifndef M7_POWERLINK_OPLKCFG_H
#define M7_POWERLINK_OPLKCFG_H
#define BENCHMARK_MODULES 0
#define DEF_DEBUG_LVL 0
#define CONFIG_INCLUDE_NMT_MN
#define CONFIG_INCLUDE_PDO
#define CONFIG_INCLUDE_SDOS
#define CONFIG_INCLUDE_SDOC
#define CONFIG_INCLUDE_SDO_ASND
#define CONFIG_INCLUDE_SDO_RW_MULTIPLE
#define CONFIG_INCLUDE_CFM
#define CONFIG_DLLCAL_QUEUE CIRCBUF_QUEUE
#define CONFIG_VETH_SET_DEFAULT_GATEWAY FALSE
#define CONFIG_CHECK_HEARTBEAT_PERIOD 1000
#define CONFIG_EDRV_AUTO_RESPONSE_DELAY FALSE
#define CONFIG_EDRV_USE_DIAGNOSTICS FALSE
#define CONFIG_DLL_PRES_CHAINING_CN FALSE
#define CONFIG_DLL_PROCESS_SYNC DLL_PROCESS_SYNC_ON_SOC
#define CONFIG_DLL_DEFERRED_RXFRAME_RELEASE_SYNC FALSE
#define CONFIG_DLL_DEFERRED_RXFRAME_RELEASE_ASYNC FALSE
#define CONFIG_OBD_CHECK_OBJECT_RANGE TRUE
#define CONFIG_OBD_USE_STRING_DOMAIN_IN_RAM TRUE
#define CONFIG_CFM_CONFIGURE_CYCLE_LENGTH TRUE
#define CONFIG_OBD_INCLUDE_A000_TO_DEVICE_PART TRUE
#define CONFIG_TIMER_USE_HIGHRES TRUE
#define CONFIG_SDO_MAX_CONNECTION_ASND 16
#define CONFIG_SDO_MAX_CONNECTION_SEQ 16
#define CONFIG_SDO_MAX_CONNECTION_COM 16
/* Configuration must be supplied from memory, not a host filesystem. */
#define OBDCDC_DISABLE_FILE_SUPPORT TRUE
#endif
