# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/openeuler/build/tl3572-2oo3/src/yocto-poky/meta \
  /home/openeuler/build/tl3572-2oo3/src/yocto-poky/../yocto-meta-openembedded/meta-oe \
  /home/openeuler/build/tl3572-2oo3/src/yocto-poky/../yocto-meta-openembedded/meta-python \
  /home/openeuler/build/tl3572-2oo3/src/yocto-poky/../yocto-meta-openembedded/meta-networking \
  /home/openeuler/build/tl3572-2oo3/src/yocto-poky/../yocto-meta-openembedded/meta-filesystems \
  /home/openeuler/build/tl3572-2oo3/src/yocto-poky/../yocto-meta-openeuler/meta-openeuler \
  /home/openeuler/build/tl3572-2oo3/src/yocto-poky/../yocto-meta-openeuler/bsp/meta-openeuler-bsp \
  /home/openeuler/build/tl3572-2oo3/src/yocto-poky/../yocto-meta-openeuler/rtos/meta-openeuler-rtos \
  /home/openeuler/build/tl3572-2oo3/src/yocto-poky/../yocto-meta-openeuler/rtos/meta-zephyr \
  /home/openeuler/build/tl3572-2oo3/meta-tl3572-stage3 \
  "
