build_in: host
machine: tl3572-evm
toolchain_type: EXTERNAL_TOOLCHAIN:aarch64
cache_src_dir:
nativesdk_dir: /opt/buildtools/nativesdk
toolchain_dir: /usr1/openeuler/gcc/openeuler_gcc_arm64le
sstate_dir: /home/openeuler/build/sstate-cache
tmp_dir: /home/openeuler/build/tl3572-2oo3/build/build-tl3572/tmp
no_layer: true
repos:
- yocto-poky
- yocto-meta-openembedded
local_conf: |+
  MCS_FEATURES ?= "openamp"
  DISTRO_FEATURES:append = " mcs"
  INIT_MANAGER = "systemd"

  DL_DIR = "/home/openeuler/build/downloads"
  BB_NUMBER_THREADS = "32"
  PARALLEL_MAKE = "-j 32"

  IMAGE_FEATURES:append = " debug-tweaks "
  KERNEL_MODULE_AUTOLOAD:remove = "mcs_km"

layers:
- yocto-meta-openeuler/rtos/meta-openeuler-rtos
- yocto-meta-openeuler/rtos/meta-zephyr
- /home/openeuler/build/tl3572-2oo3/meta-tl3572-stage3

