# TL3572 stage-3 build overrides.  This file is copied into build/conf and
# required at the end of local.conf by remote-setup-stage3.sh.
MACHINE = "tl3572-evm"
TMPDIR = "/home/openeuler/build/tl3572-2oo3/build/build-tl3572/tmp"

DL_DIR = "/home/openeuler/build/downloads"
SSTATE_DIR = "/home/openeuler/build/tl3572-2oo3/sstate-stage3"
BB_NUMBER_THREADS = "32"
PARALLEL_MAKE = "-j 32"

MCS_FEATURES ?= "openamp"
DISTRO_FEATURES:append = " mcs"
INIT_MANAGER = "systemd"
KERNEL_MODULE_AUTOLOAD:remove = "mcs_km"
